feat: hideBottomBar logic All pull requests completed after PR # 2003Migrate project to Jetpack Navigation 3 to PR #2100 Update README graphs with correct datastore-proto plugin

diff --git a/.github/workflows/Build.yaml b/.github/workflows/Build.yaml
--- a/.github/workflows/Build.yaml
+++ b/.github/workflows/Build.yaml
@@ -56,7 +56,7 @@ jobs:
         run: ./gradlew :build-logic:convention:check
 
       - name: Check spotless
-        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache
+        run: ./gradlew spotlessCheck
 
       - name: Check Dependency Guard
         id: dependencyguard_verify
@@ -107,6 +107,29 @@ jobs:
       #          file_pattern: '**/README.md'
       #          disable_globbing: true
       #          commit_message: "🤖 Updates graphs"
+
+      - name: Update Graphs
+        run: ./gradlew graphUpdate
+        continue-on-error: true
+
+      - name: Check Graphs
+        id: graphs_verify
+        run: git add -- "**/README.md" && git diff --cached --quiet --exit-code -- "**/README.md"
+
+      - name: Prevent updating graphs if this is a fork
+        id: checkfork_graphs
+        continue-on-error: false
+        if: steps.graphs_verify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Check Graphs failed, please update graphs with: ./gradlew graphUpdate" && exit 1
+
+      - name: Push new graphs if available
+        if: steps.graphs_verify.outcome == 'failure' && github.event_name == 'pull_request'
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          file_pattern: '**/README.md'
+          disable_globbing: true
+          commit_message: "🤖 Updates graphs"
 
       - name: Run all local screenshot tests (Roborazzi)
         id: screenshotsverify
